-- MySQL Script generated by MySQL Workbench
-- Fri May 14 22:02:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `chat` ;

-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat` DEFAULT CHARACTER SET utf8 ;
USE `chat` ;

-- -----------------------------------------------------
-- Table `chat`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat`.`message` ;

CREATE TABLE IF NOT EXISTS `chat`.`message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `content` TEXT(1024) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `chat`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat`.`user` ;

CREATE TABLE IF NOT EXISTS `chat`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;

USE `chat` ;

-- -----------------------------------------------------
-- Placeholder table for view `chat`.`message_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`message_view` (`message_id` INT, `content` INT, `user_id` INT, `user_name` INT, `created_at` INT);

-- -----------------------------------------------------
-- View `chat`.`message_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat`.`message_view`;
DROP VIEW IF EXISTS `chat`.`message_view` ;
USE `chat`;
CREATE  OR REPLACE VIEW `message_view` AS
SELECT
	m.id AS message_id,
    m.content AS content,
    u.id AS user_id,
    u.name AS user_name,
    m.created_at AS created_at
FROM `message` AS m
LEFT JOIN `user` AS u ON m.user_id = u.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
